library turna_app;

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:camera/camera.dart' as cam;
import 'package:audioplayers/audioplayers.dart' as ap;
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_callkit_incoming/entities/entities.dart';
import 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;
import 'package:image/image.dart' as img;
import 'package:image_picker/image_picker.dart';
import 'package:latlong2/latlong.dart' as ll;
import 'package:livekit_client/livekit_client.dart' as lk;
import 'package:local_auth/local_auth.dart';
import 'package:path_provider/path_provider.dart';
import 'package:photo_manager/photo_manager.dart' as pm;
import 'package:record/record.dart' as rec;
import 'package:shared_preferences/shared_preferences.dart';
import 'package:socket_io_client/socket_io_client.dart' as io;
import 'package:sqflite/sqflite.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:video_player/video_player.dart' as vp;

import '../core/turna_api_errors.dart';
import '../core/turna_auth.dart';
import '../core/turna_backend.dart';
import '../core/turna_contacts_directory.dart';
import '../core/turna_countries.dart';
import '../core/turna_device_context.dart';
import '../core/turna_file_utils.dart';
import '../core/turna_logging.dart';
import '../core/turna_profile_models.dart';
import '../core/turna_push.dart';
import '../core/turna_runtime_config.dart';
import '../core/turna_secure_state.dart';
import '../core/turna_telemetry.dart';
import 'turna_active_chat_registry.dart';
import 'turna_app_lock.dart';
import 'turna_bootstrap_ui.dart';
import 'turna_navigation_globals.dart';
import 'turna_shell_support.dart';
import 'turna_theme.dart';
import '../features/chat/turna_chat_models.dart';
import '../features/chat/turna_contact_models.dart';
import '../features/chat/turna_link_preview.dart';
import '../features/chat/turna_location_models.dart';
import '../features/chat/turna_media_config.dart';
import '../features/chat/turna_message_text.dart';
import '../features/calls/turna_call_models.dart';
import '../features/community/community_shell_preview.dart';
import '../features/status/turna_status_models.dart';

part 'turna_shell.dart';
part 'turna_shell_host.dart';
part 'turna_bootstrap.dart';
part 'turna_main_tabs_runtime.dart';
part 'turna_auth_flow.dart';
part 'turna_app_globals.dart';
part 'turna_app_coordinators.dart';
part '../core/turna_core.dart';
part '../core/turna_display_runtime.dart';
part '../core/turna_media_runtime.dart';
part '../core/turna_push_runtime.dart';
part '../core/turna_socket_runtime.dart';
part '../core/turna_storage.dart';
part '../core/turna_profile_api.dart';
part '../core/turna_chat_api.dart';
part '../core/turna_local_caches.dart';
part '../core/turna_upload_models.dart';
part '../features/chat/turna_inbox.dart';
part '../features/chat/turna_chat_room.dart';
part '../features/chat/turna_group_info.dart';
part '../features/chat/turna_group_settings.dart';
part '../features/chat/turna_media.dart';
part '../features/chat/turna_media_composer.dart';
part '../features/chat/turna_voice.dart';
part '../features/chat/turna_location.dart';
part '../features/chat/turna_contact.dart';
part '../features/calls/turna_calls.dart';
part '../features/calls/turna_call_runtime.dart';
part '../features/calls/turna_call_ui.dart';
part '../features/profile/turna_profile_shell.dart';
part '../features/status/turna_status.dart';
part '../features/status/turna_status_domain.dart';
part '../features/status/turna_status_feed.dart';
part '../features/status/turna_status_viewer.dart';

const String kChatRoomRouteName = 'chat-room';
