class TurnaCountry {
  const TurnaCountry({
    required this.iso,
    required this.name,
    required this.dialCode,
  });

  final String iso;
  final String name;
  final String dialCode;
}

const List<TurnaCountry> kTurnaCountries = [
  TurnaCountry(iso: 'TR', name: 'Türkiye', dialCode: '+90'),
  TurnaCountry(iso: 'GB', name: 'Birleşik Krallık', dialCode: '+44'),
  TurnaCountry(iso: 'US', name: 'Amerika Birleşik Devletleri', dialCode: '+1'),
  TurnaCountry(iso: 'CA', name: 'Kanada', dialCode: '+1'),
  TurnaCountry(iso: 'DE', name: 'Almanya', dialCode: '+49'),
  TurnaCountry(iso: 'FR', name: 'Fransa', dialCode: '+33'),
  TurnaCountry(iso: 'NL', name: 'Hollanda', dialCode: '+31'),
  TurnaCountry(iso: 'BE', name: 'Belçika', dialCode: '+32'),
  TurnaCountry(iso: 'CH', name: 'İsviçre', dialCode: '+41'),
  TurnaCountry(iso: 'AT', name: 'Avusturya', dialCode: '+43'),
  TurnaCountry(iso: 'ES', name: 'İspanya', dialCode: '+34'),
  TurnaCountry(iso: 'IT', name: 'İtalya', dialCode: '+39'),
  TurnaCountry(iso: 'IE', name: 'İrlanda', dialCode: '+353'),
  TurnaCountry(iso: 'SE', name: 'İsveç', dialCode: '+46'),
  TurnaCountry(iso: 'NO', name: 'Norveç', dialCode: '+47'),
  TurnaCountry(iso: 'DK', name: 'Danimarka', dialCode: '+45'),
  TurnaCountry(iso: 'FI', name: 'Finlandiya', dialCode: '+358'),
  TurnaCountry(iso: 'PL', name: 'Polonya', dialCode: '+48'),
  TurnaCountry(iso: 'CZ', name: 'Çekya', dialCode: '+420'),
  TurnaCountry(iso: 'RO', name: 'Romanya', dialCode: '+40'),
  TurnaCountry(iso: 'BG', name: 'Bulgaristan', dialCode: '+359'),
  TurnaCountry(iso: 'GR', name: 'Yunanistan', dialCode: '+30'),
  TurnaCountry(iso: 'CY', name: 'Kibris', dialCode: '+357'),
  TurnaCountry(iso: 'UA', name: 'Ukrayna', dialCode: '+380'),
  TurnaCountry(iso: 'RU', name: 'Rusya', dialCode: '+7'),
  TurnaCountry(iso: 'AZ', name: 'Azerbaycan', dialCode: '+994'),
  TurnaCountry(iso: 'GE', name: 'Gurcistan', dialCode: '+995'),
  TurnaCountry(iso: 'AM', name: 'Ermenistan', dialCode: '+374'),
  TurnaCountry(iso: 'AE', name: 'Birleşik Arap Emirlikleri', dialCode: '+971'),
  TurnaCountry(iso: 'SA', name: 'Suudi Arabistan', dialCode: '+966'),
  TurnaCountry(iso: 'QA', name: 'Katar', dialCode: '+974'),
  TurnaCountry(iso: 'KW', name: 'Kuveyt', dialCode: '+965'),
  TurnaCountry(iso: 'BH', name: 'Bahreyn', dialCode: '+973'),
  TurnaCountry(iso: 'OM', name: 'Umman', dialCode: '+968'),
  TurnaCountry(iso: 'IQ', name: 'Irak', dialCode: '+964'),
  TurnaCountry(iso: 'JO', name: 'Ürdün', dialCode: '+962'),
  TurnaCountry(iso: 'LB', name: 'Lübnan', dialCode: '+961'),
  TurnaCountry(iso: 'EG', name: 'Mısır', dialCode: '+20'),
  TurnaCountry(iso: 'TN', name: 'Tunus', dialCode: '+216'),
  TurnaCountry(iso: 'DZ', name: 'Cezayir', dialCode: '+213'),
  TurnaCountry(iso: 'MA', name: 'Fas', dialCode: '+212'),
  TurnaCountry(iso: 'PK', name: 'Pakistan', dialCode: '+92'),
  TurnaCountry(iso: 'IN', name: 'Hindistan', dialCode: '+91'),
  TurnaCountry(iso: 'CN', name: 'Çin', dialCode: '+86'),
  TurnaCountry(iso: 'JP', name: 'Japonya', dialCode: '+81'),
  TurnaCountry(iso: 'KR', name: 'Güney Kore', dialCode: '+82'),
  TurnaCountry(iso: 'ID', name: 'Endonezya', dialCode: '+62'),
  TurnaCountry(iso: 'MY', name: 'Malezya', dialCode: '+60'),
  TurnaCountry(iso: 'SG', name: 'Singapur', dialCode: '+65'),
  TurnaCountry(iso: 'TH', name: 'Tayland', dialCode: '+66'),
  TurnaCountry(iso: 'VN', name: 'Vietnam', dialCode: '+84'),
  TurnaCountry(iso: 'AU', name: 'Avustralya', dialCode: '+61'),
  TurnaCountry(iso: 'NZ', name: 'Yeni Zelanda', dialCode: '+64'),
  TurnaCountry(iso: 'BR', name: 'Brezilya', dialCode: '+55'),
  TurnaCountry(iso: 'AR', name: 'Arjantin', dialCode: '+54'),
  TurnaCountry(iso: 'MX', name: 'Meksika', dialCode: '+52'),
  TurnaCountry(iso: 'ZA', name: 'Güney Afrika', dialCode: '+27'),
  TurnaCountry(iso: 'NG', name: 'Nijerya', dialCode: '+234'),
  TurnaCountry(iso: 'KE', name: 'Kenya', dialCode: '+254'),
  TurnaCountry(iso: 'ET', name: 'Etiyopya', dialCode: '+251'),
];
